export enum DateRangeEnum {
  TODAY = 'Today',
  THIS_WEEK = 'This Week',
  THIS_MONTH = 'This Month',
  THIS_QUARTER = 'This Quarter',
  THIS_TRADING_YEAR = 'This Trading Year',
  THIS_YEAR = 'This Year',
  LAST_WEEK = 'Last Week',
  LAST_MONTH = 'Last Month',
  LAST_QUARTER = 'Last Quarter',
  LAST_TRADING_YEAR = 'Last Trading Year',
  LAST_YEAR = 'Last Year',
  NEXT_WEEK = 'Next Week',
  NEXT_MONTH = 'Next Month',
  NEXT_QUARTER = 'Next Quarter',
  NEXT_YEAR = 'Next Year',
  CUSTOM = 'Custom',
}
